### ISSUE TITLE
Add more issue templates

### ISSUE THREAD

**Issue by leonard84** [masooh/intellij-junit-to-spock-converter#32]
Currently the only issue template is for a conversion request, IMHO there should be some additional templates:

* Bug Report
* Feature Request

**Comment by masooh** [comment]
What would be the benefit compared to a blank issue? Bug Report maybe a list of environment questions, but feature?

But anyway, I do not see any downside, so if you have an idea for the templates I will add them.

**Comment by leonard84** [comment]
https://github.com/spockframework/spock/tree/master/.github/ISSUE_TEMPLATE

**Comment by masooh** [comment]
You're right the small blank issue link is not the obvious way if there is one template provided.

> See https://github.com/spockframework/spock/tree/master/.github/ISSUE_TEMPLATE

Could have thought of this ;-)
